# .goreleaser.yaml
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - netbsd
      - openbsd
      # - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

